### ISSUE TITLE
np.int has been deprecated

### ISSUE THREAD

**Issue by natacha-couto** [michaelkyu/MobMess#5]
Hi, I've been trying to run mobmess on a set of plasmids. I've followed your installation manual, but I've come across the following error:

Traceback (most recent call last):
  File "/well/aanensen/users/fzv779/conda/skylake/envs/mobmess/bin/mobmess", line 8, in <module>
    sys.exit(run())
  File "/well/aanensen/users/fzv779/conda/skylake/envs/mobmess/lib/python3.10/site-packages/mobmess/mobmess_script.py", line 239, in run
    args.func(args)
  File "/well/aanensen/users/fzv779/conda/skylake/envs/mobmess/lib/python3.10/site-packages/mobmess/mobmess_script.py", line 90, in infer_systems
    ani_utils.derep_sources(similarities, similarity_threshold, min_alignment_fraction,
  File "/well/aanensen/users/fzv779/conda/skylake/envs/mobmess/lib/python3.10/site-packages/mobmess/ani_utils.py", line 301, in derep_sources
    clusters_degrees = pd.Series(utils.as_flat(utils.sp_mask(sp.astype(np.int), blocks=clusters).T.dot(np.ones(sp.shape[0], dtype=np.int))), rownames)
  File "/well/aanensen/users/fzv779/conda/skylake/envs/mobmess/lib/python3.10/site-packages/numpy/__init__.py", line 319, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?

**Comment by JiabaoYuuuuu** [comment]
Hi Natacha,
I also encountered the same problem. How did you solve it? Replace all "np.int" with "int"?

**Comment by JiabaoYuuuuu** [comment]
Hi natacha,
After I replaced" np.int" with "int" "np.bool_" with "bool", mobmess is running successfully

**Comment by LauraMews** [comment]
Hey, I have the same issue, but when I replace "np.int" with "int" I get the error:
 .conda/envs/mobmess/lib/python3.10/site-packages/mobmess/ani_utils.py", line 814, in <dictcomp>
    **{k : int32 for k in ['query_start', 'query_end', 'ref_start', 'ref_end', 'errors', 'mismatches', 'nonalpha', 'query_len', 'ref_len']}})    
NameError: name 'int32' is not defined
Did you also encounter that or just changed the whole thing for int32 and int64 to something else?

**Comment by drelo** [comment]
Hi all, could anyone help us to fix this issue,  I recently installed MobMess following the instructions here.  

Both the example and our data fail at this step 

`mobmess systems -s all_bacteria.fasta -c bacteria-circular2.txt -o OUTmobmess
`
@JiabaoYuuuuu could you guide me to understand which file/s need this replacement? 
We are experiencing the same issue as @LauraMews after that replacement

Thanks

Andrés


**Here is the current environment:** 


> # packages in environment at /home/nriera/miniforge3/envs/mobmess:
> #
> # Name                    Version                   Build  Channel
> _libgcc_mutex             0.1                 conda_forge    conda-forge
> _openmp_mutex             4.5                       2_gnu    conda-forge
> blas                      1.0                    openblas    anaconda
> blosc                     1.21.3               h6a678d5_0    anaconda
> bottleneck                1.4.2           py312ha883a20_0    anaconda
> brotli                    1.0.9                h166bdaf_7    conda-forge
> brotli-bin                1.0.9                h166bdaf_7    conda-forge
> bzip2                     1.0.8                h5eee18b_6    anaconda
> ca-certificates           2024.12.31           h06a4308_0    anaconda
> contourpy                 1.3.1           py312hdb19cb5_0  
> cycler                    0.12.1             pyhd8ed1ab_1    conda-forge
> dataclasses               0.8                pyhc8e2a94_3    conda-forge
> expat                     2.6.4                h6a678d5_0    anaconda
> fontconfig                2.14.0               h8e229c2_0    conda-forge
> fonttools                 4.55.3             pyhe1237c8_1    conda-forge
> freetype                  2.10.4               h0708190_1    conda-forge
> gmp                       6.2.1                h295c915_3    anaconda
> icu                       58.2                 he6710b0_3    anaconda
> igraph                    0.11.8                   pypi_0    pypi
> jinja2                    3.1.5              pyhd8ed1ab_0    conda-forge
> joblib                    1.4.2           py312h06a4308_0    anaconda
> jpeg                      9e                   h166bdaf_1    conda-forge
> kiwisolver                1.4.8           py312h6a678d5_0  
> lcms2                     2.16                 hb9589c4_0  
> ld_impl_linux-64          2.40                 h12ee557_0    anaconda
> lerc                      4.0.0                h6a678d5_0  
> libbrotlicommon           1.0.9                h166bdaf_7    conda-forge
> libbrotlidec              1.0.9                h166bdaf_7    conda-forge
> libbrotlienc              1.0.9                h166bdaf_7    conda-forge
> libdeflate                1.22                 h5eee18b_0  
> libexpat                  2.6.4                h5888daf_0    conda-forge
> libffi                    3.4.4                h6a678d5_1    anaconda
> libgcc                    14.2.0               h77fa898_1    conda-forge
> libgcc-ng                 14.2.0               h69a702a_1    conda-forge
> libgfortran-ng            11.2.0               h00389a5_1    anaconda
> libgfortran5              11.2.0               h1234567_1    anaconda
> libgomp                   14.2.0               h77fa898_1    conda-forge
> libiconv                  1.16                 h5eee18b_3    anaconda
> libllvm14                 14.0.6               hecde1de_4    anaconda
> libnsl                    2.0.0                h5eee18b_0    anaconda
> libopenblas               0.3.21               h043d6bf_0    anaconda
> libpng                    1.6.39               h5eee18b_0  
> libsqlite                 3.46.0               hde9e2c9_0    conda-forge
> libstdcxx                 14.2.0               hc0a3c3a_1    conda-forge
> libstdcxx-ng              14.2.0               h4852527_1    conda-forge
> libtiff                   4.5.1                hffd6297_1
> 
> libuuid                   2.38.1               h0b41bf4_0    conda-forge
> libwebp-base              1.3.2                h5eee18b_1  
> libxcb                    1.17.0               h8a09558_0    conda-forge
> libxml2                   2.10.4               hcbfbd50_0    anaconda
> libzlib                   1.2.13               h4ab18f5_6    conda-forge
> llvmlite                  0.43.0          py312h6a678d5_1    anaconda
> lz4-c                     1.9.4                h6a678d5_1    anaconda
> markupsafe                3.0.2           py312h178313f_1    conda-forge
> matplotlib-base           3.10.0          py312hbfdbfaf_0  
> mobmess                   0.0.0                    pypi_0    pypi
> mummer4                   4.0.0rc1        pl5321h87f3376_3    bioconda
> munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
> ncurses                   6.4                  h6a678d5_0    anaconda
> numba                     0.60.0          py312h83e6fd3_0    conda-forge
> numexpr                   2.10.1          py312hd28fd6d_0    anaconda
> numpy                     1.26.4          py312h2809609_0    anaconda
> numpy-base                1.26.4          py312he1a6c75_0    anaconda
> openjpeg                  2.5.2                he7f1fd0_0  
> openssl                   3.4.0                h7b32b05_1    conda-forge
> packaging                 24.2               pyhd8ed1ab_2    conda-forge
> pandas                    2.2.3           py312h6a678d5_0    anaconda
> patsy                     1.0.1              pyhd8ed1ab_1    conda-forge
> pdfkit                    1.0.0                    pypi_0    pypi
> perl                      5.32.1          0_h5eee18b_perl5    anaconda
> pillow                    11.0.0          py312hcea889d_1  
> pip                       24.2            py312h06a4308_0    anaconda
> plasx                     0.0.0                    pypi_0    pypi
> pthread-stubs             0.4               hb9d3cd8_1002    conda-forge
> pyparsing                 3.2.1              pyhd8ed1ab_0    conda-forge
> pypdf2                    3.0.1              pyhd8ed1ab_1    conda-forge
> python                    3.12.0          hab00c5b_0_cpython    conda-forge
> python-blosc              1.10.6          py312h526ad5a_0    anaconda
> python-dateutil           2.9.0post0      py312h06a4308_2    anaconda
> python-tzdata             2023.3             pyhd3eb1b0_0    anaconda
> python_abi                3.12                    5_cp312    conda-forge
> pytz                      2024.1          py312h06a4308_0    anaconda
> readline                  8.2                  h5eee18b_0    anaconda
> scikit-learn              1.5.2           py312h6a678d5_0    anaconda
> scipy                     1.14.1          py312h2809609_0    anaconda
> seaborn                   0.13.2               hd8ed1ab_3    conda-forge
> seaborn-base              0.13.2             pyhd8ed1ab_3    conda-forge
> setuptools                75.1.0          py312h06a4308_0    anaconda
> six                       1.16.0             pyhd3eb1b0_1    anaconda
> sqlite                    3.45.3               h5eee18b_0    anaconda
> statsmodels               0.14.4          py312h5eee18b_0  
> tbb                       2021.8.0             hdb19cb5_0    anaconda
> texttable                 1.7.0                    pypi_0    pypi
> threadpoolctl             3.5.0           py312he106c6f_0    anaconda
> tk                        8.6.14               h39e8969_0    anaconda
> typing_extensions         4.12.2             pyha770c72_1    conda-forge
> tzdata                    2024b                h04d1e81_0    anaconda
> unicodedata2              15.1.0          py312h5eee18b_1  
> wheel                     0.44.0          py312h06a4308_0    anaconda
> wkhtmltopdf               0.12.4                        1    conda-forge
> xorg-libx11               1.8.10               h4f16b4b_1    conda-forge
> xorg-libxau               1.0.12               hb9d3cd8_0    conda-forge
> xorg-libxdmcp             1.1.5                hb9d3cd8_0    conda-forge
> xorg-libxext              1.3.6                hb9d3cd8_0    conda-forge
> xorg-libxrender           0.9.12               hb9d3cd8_0    conda-forge
> xz                        5.4.6                h5eee18b_1    anaconda
> zlib                      1.2.13               h4ab18f5_6    conda-forge
> zstd                      1.5.6                hc292b87_0    anaconda

**Comment by wangL5** [comment]
I had this same issue. What ended up working for me was replacing "np.int" in the ani_utils.py script with "int". Importantly, I didn't touch np.int32 or np.int64. I just replaced "np.int" with "int" in line 301 and line 352.
