### ISSUE TITLE
Visualisation fails

### ISSUE THREAD

**Issue by thh32** [michaelkyu/MobMess#7]
Hey,

Currently the visualisation seems to have some errors and provides no output.

Best,
Tom

`mobmess visualize -s test-contigs.fa -a test-contigs-annotations.txt --contigs $contigs --threads 10 --output Figure-5D-genome-visualization.pdf 
Plotting contigs: CHI0047_000000002374 CHI0169_000000002212 ENG0179_000000005290 FIJ0137_000000001400 ISR0036_000000000921 ISR0117_000000003149 ISR0179_000000003111 ISR0266_000000001592 ISR0775_000000002602 MON0062_000000008770 USA0022_01_000000001239
Skipping merge of gene calls and functions
functions columns: ['contig', 'start', 'stop', 'direction', 'accession', 'source', 'description']
Input contigs: 11
/home/thomashitch/miniconda3/envs/mobmess/lib/python3.10/site-packages/plasx/pd_utils.py:776: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(df[c]):
Contigs in functions: 11
Input 0 anchor genes: (10:59:23)
Adding 1 anchors genes: (10:59:23)
Anchor gene families: ['COG4115']
/home/thomashitch/miniconda3/envs/mobmess/lib/python3.10/site-packages/plasx/pd_utils.py:776: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(df[c]):
Total loci: 11
neighborhood: 20000
/home/thomashitch/miniconda3/envs/mobmess/lib/python3.10/site-packages/mobmess/plot.py:2706: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  return functions.groupby('contig', as_index=False, group_keys=False).apply(interval_merge_same_contig).reset_index(drop=True)
Loci after merging: 11
Contigs to be plotted: 11 (10:59:23)
Handling loci that may have multiple instances of the anchor genes(s) (10:59:23)
Intersecting loci (10:59:23)
/home/thomashitch/miniconda3/envs/mobmess/lib/python3.10/site-packages/mobmess/plot.py:2791: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  contig_2_functions = {k : v for k, v in functions.groupby('contig')}
/home/thomashitch/miniconda3/envs/mobmess/lib/python3.10/site-packages/mobmess/plot.py:2792: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  contig_2_functions2 = {k : v for k, v in functions2.groupby('contig')}
Traceback (most recent call last):
  File "/home/thomashitch/miniconda3/envs/mobmess/bin/mobmess", line 8, in <module>
    sys.exit(run())
  File "/home/thomashitch/miniconda3/envs/mobmess/lib/python3.10/site-packages/mobmess/mobmess_script.py", line 239, in run
    args.func(args)
  File "/home/thomashitch/miniconda3/envs/mobmess/lib/python3.10/site-packages/mobmess/mobmess_script.py", line 129, in visualize
    plot.visualize_alignment(
  File "/home/thomashitch/miniconda3/envs/mobmess/lib/python3.10/site-packages/mobmess/plot.py", line 1803, in visualize_alignment
    intersect_bed = interval_merge(genes_encompassing, loci, suffix='loci')
  File "/home/thomashitch/miniconda3/envs/mobmess/lib/python3.10/site-packages/mobmess/plot.py", line 2796, in interval_merge
    merged_intervals.append(interval_merge_same_contig(contig_2_functions[contig], contig_2_functions2[contig], suffix=suffix))
  File "/home/thomashitch/miniconda3/envs/mobmess/lib/python3.10/site-packages/mobmess/plot.py", line 2756, in interval_merge_same_contig
    functions_merged = pd.concat([functions_repeated, functions2_repeated], 1)
TypeError: concat() takes 1 positional argument but 2 were given
`

**Comment by braddmg** [comment]
Not sure, but provide what you save in the $contigs variable just to be sure. Also revise you are using the right annotations.txt
